### ISSUE TITLE
segment functionalities

### ISSUE THREAD

**Issue by LinguList** [lingpy/linse#1]
- [x] lingpy.sequence.soundclasses.ipa2tokens
- [x] lingpy.sequence.soundclasses.asjp2tokens (not important but potentially useful ?)
- lingpy.sequence.soundclasses.sampa2uni (potentially useful)

**Comment by LinguList** [comment]
* lingpy.sequence.soundlcasses.clean_string (we used that in lexibank, I think, in the past, but one can debate the importance of such a function)

**Comment by xrotwang** [comment]
Looking at `clean_string`, it seems that it's mostly a shallow wrapper around `ipa2tokens`. So I'd say we either could copy the wrapping code into `pylexibank` or simply call `linse.segment.ipa` instead of `lingpy.clean_string` from within `pylexibank`.

**Comment by LinguList** [comment]
Yes, I agree.
