### ISSUE TITLE
Profile module: utility functions to create intitial profiles

### ISSUE THREAD

**Issue by LinguList** [lingpy/linse#5]
we have currently three functions:

- simple profile (without context)
- context profile (with context)

and

- sea profile (with structure, currently only in sinopy)

Missing functionalities in the first two profiles:

- language specific profiles

Functionalities to be enhanced:

- code not based on lingpy's wordlists, but rather on CSV reading of a file, specifying the column in which the text is, and the column in which the language is to be expected
- output possibilities could be enhanced by allowing to deselect frequencies or other aspects (but this is not the most important aspec)

**Comment by LinguList** [comment]
@xrotwang, if you do not mind, I'd self-assign this, writing the basic function that reads in csv file and returns a profile in the different variants. The integration with commandline is something where I'd rather follow your suggestions, as I find these often tricky to test.

**Comment by xrotwang** [comment]
Ok. We should keep it simple, though. From my experience with the functions in `sound_classes`, we should stay away from mixing input/output and logic. All the `if output == ...` branches really detract from the core business.

**Comment by xrotwang** [comment]
The serialization of what should be nested lists as `... ... + ... _ ...` seems to be an instance of the same problem, which even forces each function to deal with input/output and formatting.

**Comment by LinguList** [comment]
Yes, this was my plan. I'd say: we can even say that we have minimal input to the function, such as: ID, Concept, Language, Form (and Form is configurable, but defaults to "Form"). 

So if one wants to create a profile, the call would be something like `get_profile(list_of_dicts, **kw)` and it would return a dictionary with graphemes as key and a dictionary as values?

Filtering by language would then be passed in a step before, e.g., when creating the `dicts`.

**Comment by LinguList** [comment]
> The serialization of what should be nested lists as ... ... + ... _ ... seems to be an instance of the same problem, which even forces each function to deal with input/output and formatting.

This is an extreme nightmare now, also since I wanted to support multiple morpheme separators in the past, it is good to really get rid of this.

**Comment by xrotwang** [comment]
Regarding the `get_profile` signature: Why would it need `ID`, `Concept` and `Language`? To add examples as documentation to the profile? If so, I'd even think of something more generic, e.g. a class (or custom subclass of)
```python
class Form:
    def __str__(self):  # the actual form
    def example(self):  # may use any other attributes of the class to format this as example in the profile
```

Then we could support the most simple use case `get_profile(*forms)` in the simplest form.

**Comment by LinguList** [comment]
Yes, this is a good idea. One reason I wanted the ID was that it is difficult to debug the current code for profile creation if things go wrong in the original word list. Tracing un-segmentable forms (so they can be placed into our lexemes.csv files) is something important for practical work. 

If we have such a class form, would we assume it is like the generic Saussure model of the linguistic sign: having a language, and a concept as attributes? Then one could even make a class "sign", which is instantiated by a triple of language, concept, and form?

**Comment by xrotwang** [comment]
Hm. I'd rather keep the explicit attributes to a minimum, and instead maybe give it a "bag of things" attribute, which could store all sorts of other data passed at initialization. The debug use case could then be satisfied by just including this bag in (verbose) debug output. But if none of the profile-creation logic uses language or concept, I'd rather not use these.

**Comment by LinguList** [comment]
Well, in fact, you are right: the profile is indifferent as to what the concept is, etc., for the profile, only the form counts, and one could even take a set of forms, not a list, as we don't really care. The filtering by language, the debugging by concept, etc., and the actual writing of the profile with additional counts could be done once the profile (a dictionary with identified graphemes as key and our forms as values) is done. we could even collect bad forms, where profile creation failed, under some key, e.g., "?".
