### ISSUE TITLE
Move ngram/smoothing code from lingpy?

### ISSUE THREAD

**Issue by tresoldi** [lingpy/linse#9]
We have some support for ngrams and ngrams models (along with smoothing methods) in `lingpy`:

- ngrams: https://github.com/lingpy/lingpy/blob/master/lingpy/sequence/ngrams.py (tests: https://github.com/lingpy/lingpy/blob/master/lingpy/tests/sequence/test_ngrams.py)
- smoothing: https://github.com/lingpy/lingpy/blob/master/lingpy/sequence/smoothing.py (tests: https://github.com/lingpy/lingpy/blob/master/lingpy/tests/sequence/test_smoothing.py)

They were first developed as an alternative to NLTK, but don't work as a drop-in replacement. Immediate work would include new methods for entropy (currently only computing per-sequence [and not per state] entropy, and corrected by the distribution of sequence lengths) and other smoothing methods (at least Kneser-Ney).

Should we consider moving them from `lingpy` into `linse`? Or should we remove them from lingpy and release a small, stand-alone library?

**Comment by LinguList** [comment]
I think, this would go beyond the purpose of linse, since we plan to
have manipulation of sequences here, not statistics or comparison, or
generation. So I rather propose to put ngrams in their own package.

**Comment by tresoldi** [comment]
Sure, can always have some tests/demo using the four main libraries (ngram/linse/lingpy/cldf). Closing the issue.
